kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
  #if you do not provide namespace then container will be created in default namespace
spec:
#one pod can contain mutliple containers
  containers:
  - name: nginx
    image: nginx