kind: Service
apiVersion: v1
metadata:
  name: nginx  #service name
spec:
  type: NodePort
  selector: # labels are used as selectors
    project: expense
    component: backend
    enviornment: dev
    version: "1.0.0"  #this service (nginx) will get attached whatever the pod have these labels 
    demo: nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    enviornment: dev
    version: "1.0.0"
    demo: nodeport
spec:
  containers:
  - name: nginx
    image: nginx